<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Panned.Translit.Contracts\Panned.Translit.Contracts.csproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="$(ProjectDir)\..\Panned.Translit.CodeGenerator\$(OutputPath)\Panned.Translit.CodeGenerator.exe $(ProjectDir)\..\xml $(ProjectDir)" />
  </Target>

</Project>
